(()=>{
 if(window.__apiLensPageSnifferLoaded)return;window.__apiLensPageSnifferLoaded=true;
 let enabled=false,snapshotted=false;const MAX_BODY=200000;
 const headersObj=h=>{const o={};try{new Headers(h||{}).forEach((v,k)=>o[k]=v)}catch{}return o};
 const trim=s=>{s=String(s??'');return s.length>MAX_BODY?s.slice(0,MAX_BODY)+`\n… [truncated ${s.length-MAX_BODY} chars]`:s};
 function bodyText(b){try{if(b==null)return'';if(typeof b==='string')return trim(b);if(b instanceof URLSearchParams)return trim(b.toString());if(b instanceof FormData)return trim(JSON.stringify([...b.entries()].map(([k,v])=>[k,typeof v==='string'?v:`[File ${v.name||''} ${v.size||0} bytes]`])));if(b instanceof Blob)return`[Blob ${b.type||'unknown'} ${b.size} bytes]`;if(b instanceof ArrayBuffer||ArrayBuffer.isView(b))return`[Binary ${b.byteLength||b.length||0} bytes]`;return trim(String(b))}catch{return'[unavailable]'}}
 function post(entry){if(!enabled)return;window.postMessage({source:'api-lens-sniffer',type:'ENTRY',entry:{...entry,pageUrl:location.href,pageTitle:document.title,capturedAt:Date.now()}},'*')}
 async function responseBody(resp){try{const ct=resp.headers.get('content-type')||'',len=Number(resp.headers.get('content-length')||0);if(len>MAX_BODY)return`[body skipped: ${len} bytes]`;if(!/json|text|xml|javascript|x-www-form-urlencoded|graphql/i.test(ct)&&len>0)return`[non-text body: ${ct||'unknown'}, ${len} bytes]`;return trim(await resp.clone().text())}catch(e){return`[response body unavailable: ${e.message}]`}}
 const originalFetch=window.fetch.bind(window);
 window.fetch=async function(input,init={}){if(!enabled)return originalFetch(input,init);const started=performance.now(),req=input instanceof Request?input:null,url=req?.url||String(input),method=(init.method||req?.method||'GET').toUpperCase(),requestHeaders={...headersObj(req?.headers),...headersObj(init.headers)},requestBody=bodyText(init.body),stack=(new Error().stack||'').split('\n').slice(2,8).join('\n');try{const resp=await originalFetch(input,init);const base={kind:'fetch',method,url,status:resp.status,statusText:resp.statusText,ok:resp.ok,duration:performance.now()-started,requestHeaders,requestBody,responseHeaders:headersObj(resp.headers),contentType:resp.headers.get('content-type')||'',size:Number(resp.headers.get('content-length')||0),initiator:'fetch',stack};responseBody(resp).then(rb=>post({...base,responseBody:rb})).catch(()=>post({...base,responseBody:'[response body unavailable]'}));return resp}catch(e){post({kind:'fetch',method,url,status:0,statusText:'FETCH ERROR',ok:false,duration:performance.now()-started,requestHeaders,requestBody,responseHeaders:{},responseBody:'',contentType:'',size:0,initiator:'fetch',error:e.message,stack});throw e}}
 const XO=XMLHttpRequest.prototype.open,XS=XMLHttpRequest.prototype.send,XH=XMLHttpRequest.prototype.setRequestHeader;
 XMLHttpRequest.prototype.open=function(method,url,...rest){this.__apiLens={method:String(method||'GET').toUpperCase(),url:new URL(String(url),location.href).href,headers:{}};return XO.call(this,method,url,...rest)};
 XMLHttpRequest.prototype.setRequestHeader=function(k,v){if(this.__apiLens)this.__apiLens.headers[String(k).toLowerCase()]=String(v);return XH.call(this,k,v)};
 XMLHttpRequest.prototype.send=function(body){const meta=this.__apiLens||{method:'GET',url:'',headers:{}},active=enabled,started=performance.now();if(active){meta.requestBody=bodyText(body);meta.stack=(new Error().stack||'').split('\n').slice(2,8).join('\n');this.addEventListener('loadend',()=>{let rb='';try{if(this.responseType===''||this.responseType==='text')rb=trim(this.responseText||'');else if(this.responseType==='json')rb=trim(JSON.stringify(this.response));else rb=`[${this.responseType||'binary'} response]`}catch(e){rb=`[response body unavailable: ${e.message}]`}let rhs={};try{for(const line of(this.getAllResponseHeaders()||'').trim().split(/\r?\n/)){const i=line.indexOf(':');if(i>0)rhs[line.slice(0,i).trim().toLowerCase()]=line.slice(i+1).trim()}}catch{}post({kind:'xhr',method:meta.method,url:meta.url,status:this.status,statusText:this.statusText,ok:this.status>=200&&this.status<400,duration:performance.now()-started,requestHeaders:meta.headers,requestBody:meta.requestBody,responseHeaders:rhs,responseBody:rb,contentType:this.getResponseHeader('content-type')||'',size:Number(this.getResponseHeader('content-length')||0),initiator:'xmlhttprequest',stack:meta.stack})},{once:true})}return XS.call(this,body)};
 function resourceEntry(e,historical=false){post({kind:'resource',method:'GET',url:e.name,status:0,statusText:historical?'Existing resource':'Resource',ok:true,duration:e.duration||0,requestHeaders:{},requestBody:'',responseHeaders:{},responseBody:'',contentType:'',size:e.transferSize||e.encodedBodySize||0,initiator:e.initiatorType||'resource',startTime:e.startTime||0,historical})}
 try{new PerformanceObserver(list=>{if(!enabled)return;for(const e of list.getEntries())if(!['fetch','xmlhttprequest'].includes(e.initiatorType))resourceEntry(e,false)}).observe({type:'resource',buffered:false})}catch{}
 function snapshot(){if(snapshotted)return;snapshotted=true;try{performance.getEntriesByType('resource').slice(-120).forEach(e=>{if(!['fetch','xmlhttprequest'].includes(e.initiatorType))resourceEntry(e,true)})}catch{}}
 window.addEventListener('message',e=>{if(e.source!==window||e.data?.source!=='api-lens-control'||e.data.type!=='SET_ENABLED')return;enabled=!!e.data.enabled;if(enabled)snapshot()});
})();
