let last=null,view="pretty";const $=x=>document.getElementById(x);
const esc=x=>String(x??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function responseFilename(){const ct=last?.contentType||"";if(ct.includes("json"))return"api-response.json";if(ct.includes("html"))return"api-response.html";if(ct.includes("xml"))return"api-response.xml";return"api-response.txt"}
function render(){if(!last)return;const o=$("out");if(view==="raw"){o.textContent=last.text;return}if(view==="headers"){o.textContent=Object.entries(last.responseHeaders).map(([k,v])=>`${k}: ${v}`).join("\n");return}if(view==="pretty"){o.textContent=last.json!==null?JSON.stringify(last.json,null,2):last.text;return}const a=Array.isArray(last.json)?last.json:(last.json&&typeof last.json==="object"?[last.json]:null);if(!a){o.textContent="Table view requires a JSON object or array.";return}const keys=[...new Set(a.slice(0,100).flatMap(x=>x&&typeof x==="object"&&!Array.isArray(x)?Object.keys(x):[]))].slice(0,30);if(!keys.length){o.textContent="No tabular object fields found.";return}o.innerHTML=`<table><thead><tr>${keys.map(k=>`<th>${esc(k)}</th>`).join("")}</tr></thead><tbody>${a.slice(0,100).map(r=>`<tr>${keys.map(k=>`<td>${esc(typeof r?.[k]==="object"?JSON.stringify(r[k]):r?.[k])}</td>`).join("")}</tr>`).join("")}</tbody></table>`}
async function addRecent(req){let {apiLensRecent=[]}=await chrome.storage.local.get("apiLensRecent");apiLensRecent=apiLensRecent.filter(x=>!(x.method===req.method&&x.url===req.url));apiLensRecent.unshift({...req,saved:false,at:Date.now()});await chrome.storage.local.set({apiLensRecent:apiLensRecent.slice(0,12)});renderSaved()}
async function renderSaved(){let {apiLensSaved=[],apiLensRecent=[]}=await chrome.storage.local.get(["apiLensSaved","apiLensRecent"]);const rows=[...apiLensSaved.map((x,i)=>({...x,kind:"saved",i})),...apiLensRecent.map((x,i)=>({...x,kind:"recent",i}))];$("saved").innerHTML=rows.map(x=>`<div class="fav ${x.kind}"><button data-load="${x.kind}:${x.i}">${esc(x.method)} ${esc(x.url)}</button><button class="star" data-del="${x.kind}:${x.i}">${x.kind==="saved"?"★":"×"}</button></div>`).join("")||"<span style='color:#64748b'>No saved or recent requests.</span>";document.querySelectorAll("[data-load]").forEach(b=>b.onclick=async()=>{const[k,i]=b.dataset.load.split(":");const data=await chrome.storage.local.get(k==="saved"?"apiLensSaved":"apiLensRecent"),arr=data[k==="saved"?"apiLensSaved":"apiLensRecent"]||[],f=arr[+i];if(!f)return;$("method").value=f.method;$("url").value=f.url;$("headers").value=f.headers||"{}";$("body").value=f.body||""});document.querySelectorAll("[data-del]").forEach(b=>b.onclick=async()=>{const[k,i]=b.dataset.del.split(":");const key=k==="saved"?"apiLensSaved":"apiLensRecent",data=await chrome.storage.local.get(key),arr=data[key]||[];arr.splice(+i,1);await chrome.storage.local.set({[key]:arr});renderSaved()})}
async function send(){const url=$("url").value.trim();if(!url)return;const method=$("method").value,t=performance.now();$("status").textContent="Sending…";$("meta").className="";try{let headers;try{headers=JSON.parse($("headers").value||"{}")}catch{throw new Error("Headers must be valid JSON.")}const opt={method,headers,cache:"no-store"};if(!["GET","HEAD"].includes(method)&&$("body").value)opt.body=$("body").value;const r=await fetch(url,opt),text=await r.text(),responseHeaders={};r.headers.forEach((v,k)=>responseHeaders[k]=v);let json=null;try{json=JSON.parse(text)}catch{}last={text,json,responseHeaders,status:r.status,statusText:r.statusText,contentType:r.headers.get("content-type")||""};const ms=Math.round(performance.now()-t);$("meta").textContent=`HTTP ${r.status} ${r.statusText} • ${ms} ms • ${text.length.toLocaleString()} chars • ${last.contentType||"unknown type"}`;$("meta").className=r.ok?"ok":"error";$("status").textContent=r.ok?"Success":"HTTP error";render();await addRecent({method,url,headers:$("headers").value,body:$("body").value})}catch(e){last=null;$("status").textContent="Failed";$("meta").textContent="";$("out").textContent=`Request failed: ${e.message}\n\nPossible causes: network failure, invalid URL, authentication, TLS/certificate issues, or the endpoint rejecting extension-origin requests.`}}
$("send").onclick=send;$("url").onkeydown=e=>{if(e.key==="Enter")send()};
document.querySelectorAll("nav button[data-v]").forEach(b=>b.onclick=()=>{view=b.dataset.v;document.querySelectorAll("nav button[data-v]").forEach(x=>x.classList.toggle("on",x===b));render()});
$("copy").onclick=async()=>{if(!last)return;const text=view==="headers"?Object.entries(last.responseHeaders).map(([k,v])=>`${k}: ${v}`).join("\n"):view==="pretty"&&last.json!==null?JSON.stringify(last.json,null,2):last.text;await navigator.clipboard.writeText(text);$("copy").textContent="Copied ✓";setTimeout(()=>$("copy").textContent="Copy",800)};
$("download").onclick=()=>{if(!last)return;const blob=new Blob([last.text],{type:last.contentType||"text/plain"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=responseFilename();a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
$("save").onclick=async()=>{const req={method:$("method").value,url:$("url").value,headers:$("headers").value,body:$("body").value};if(!req.url)return;let {apiLensSaved=[]}=await chrome.storage.local.get("apiLensSaved");apiLensSaved=apiLensSaved.filter(x=>!(x.method===req.method&&x.url===req.url));apiLensSaved.unshift(req);await chrome.storage.local.set({apiLensSaved:apiLensSaved.slice(0,25)});renderSaved()};
$("clearHistory").onclick=async()=>{await chrome.storage.local.set({apiLensRecent:[]});renderSaved()};
$("clear").onclick=()=>{$("url").value="";$("headers").value="{}";$("body").value="";$("meta").textContent="";$("out").textContent="Enter an API URL and press SEND.";last=null};
document.querySelectorAll("[data-example]").forEach(b=>b.onclick=()=>{if(b.dataset.example==="json"){$("method").value="GET";$("url").value="https://jsonplaceholder.typicode.com/todos/1"}else{$("method").value="GET";$("url").value="https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard"}});
renderSaved();
