const KEY='clipboardBuddyItems', MAX=250, $=id=>document.getElementById(id);
let items=[];
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
async function load(){({[KEY]:items=[]}=await chrome.storage.local.get(KEY));render()}
async function persist(){items=items.slice(0,MAX);await chrome.storage.local.set({[KEY]:items});render()}
function make(text,tags=[],source='manual'){const clean=String(text||'').trim();if(!clean)return null;return{id:crypto.randomUUID(),text:clean,title:clean.split(/\r?\n/)[0].slice(0,72),tags,pinned:false,source,createdAt:Date.now(),updatedAt:Date.now()}}
async function add(text,tags=[],source='manual'){const x=make(text,tags,source);if(!x)return;items=items.filter(i=>i.text!==x.text);items.unshift(x);await persist()}
function render(){const q=$('search').value.trim().toLowerCase();const rows=items.filter(x=>!q||[x.text,x.title,(x.tags||[]).join(' '),x.source].join(' ').toLowerCase().includes(q)).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.updatedAt-a.updatedAt);$('stats').textContent=`${items.length} saved • ${items.filter(x=>x.pinned).length} pinned • ${rows.length} shown`;$('list').innerHTML=rows.length?rows.map(x=>`<div class="item ${x.pinned?'pinned':''}" data-id="${x.id}"><div class="top"><span>${x.pinned?'⭐':'📄'}</span><div class="title">${esc(x.title||'Snippet')}</div><span class="badge">${esc(x.source||'saved')}</span></div><div class="text">${esc(x.text)}</div><div class="tags">${(x.tags||[]).map(t=>'#'+esc(t)).join(' ')}</div><div class="actions"><button data-act="copy">Copy</button><button data-act="pin">${x.pinned?'Unpin':'Pin'}</button><button data-act="edit">Edit</button><button data-act="delete">Delete</button></div></div>`).join(''):'<div class="empty">No matching snippets.</div>';
 document.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>act(b.closest('.item').dataset.id,b.dataset.act));}
async function act(id,action){const x=items.find(i=>i.id===id);if(!x)return;if(action==='copy'){await navigator.clipboard.writeText(x.text);x.updatedAt=Date.now();await persist();return}if(action==='pin'){x.pinned=!x.pinned;x.updatedAt=Date.now();await persist();return}if(action==='delete'){items=items.filter(i=>i.id!==id);await persist();return}if(action==='edit'){const text=prompt('Edit snippet',x.text);if(text===null)return;const tags=prompt('Tags (comma separated)',(x.tags||[]).join(', '));x.text=text.trim();x.title=x.text.split(/\r?\n/)[0].slice(0,72);x.tags=(tags||'').split(',').map(s=>s.trim()).filter(Boolean);x.updatedAt=Date.now();await persist()}}
$('capture').onclick=async()=>{try{const text=await navigator.clipboard.readText();if(!text.trim())return alert('Clipboard contains no text.');await add(text,[],'clipboard')}catch(e){alert('Chrome blocked clipboard reading. Click the extension popup and try again: '+e.message)}};
$('add').onclick=async()=>{await add($('manual').value,$('tags').value.split(',').map(s=>s.trim()).filter(Boolean));$('manual').value='';$('tags').value=''};
$('clear').onclick=async()=>{if(!confirm('Delete all unpinned snippets?'))return;items=items.filter(x=>x.pinned);await persist()};$('search').oninput=render;load();
