const $=id=>document.getElementById(id);
const printable=s=>{if(!s)return false;let good=0;for(const c of s)if(/[\t\n\r\x20-\x7E]/.test(c))good++;return good/s.length>.9};
function b64decode(s,url=false){let x=s.trim();if(url)x=x.replace(/-/g,'+').replace(/_/g,'/');while(x.length%4)x+='=';const bin=atob(x),bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
function detect(s){const t=s.trim();if(!t)return'text';if(/^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/.test(t)){try{JSON.parse(b64decode(t.split('.')[0],true));JSON.parse(b64decode(t.split('.')[1],true));return'jwt'}catch{}}
 try{JSON.parse(t);return'json'}catch{}
 try{const u=new URL(t);if(u.protocol==='http:'||u.protocol==='https:')return'url'}catch{}
 if(/^([?]?[^\s=&]+=[^\n&]*&?){2,}$/.test(t))return'query';
 if(/^<\?xml|<[^>]+>[\s\S]*<\/[^>]+>$/i.test(t))return /^<!doctype html|<html[\s>]|<body[\s>]|<div[\s>]|<span[\s>]/i.test(t)?'html':'xml';
 if(/[{}][\s\S]*:[^;{}]+;/.test(t)&&!/=>|function\s|const\s|let\s|var\s/.test(t))return'css';
 if(/\b(select|insert|update|delete|create|alter|with)\b[\s\S]*\b(from|into|table|set|as)\b/i.test(t))return'sql';
 const lines=t.split(/\r?\n/);if(lines.length>1){const tabs=lines.filter(x=>x.includes('\t')).length,commas=lines.filter(x=>x.includes(',')).length;if(tabs/lines.length>.7)return'tsv';if(commas/lines.length>.7)return'csv';if(lines.filter(x=>/^\s*(\[?\d{2}:\d{2}|\d{4}-\d{2}-\d{2}|INFO|WARN|ERROR|DEBUG)/i.test(x)).length/lines.length>.4)return'log'}
 if(/\\[nrt"]|\\u[0-9a-f]{4}/i.test(t))return'escaped';
 if(/^[A-Za-z0-9+/=_-]{20,}$/.test(t)&&t.length%4!==1){try{const d=b64decode(t,/[-_]/.test(t));if(printable(d))return'base64'}catch{}}
 return'text'}
function prettyMarkup(s){const tokens=s.replace(/>\s*</g,'><').split(/(?=<)|(?<=>)/).filter(Boolean);let depth=0,out=[];for(const tok of tokens){const x=tok.trim();if(!x)continue;if(/^<\/(?!br|hr)/i.test(x))depth=Math.max(0,depth-1);out.push('  '.repeat(depth)+x);if(/^<[^!?/][^>]*[^/]>/i.test(x)&&!/^<(area|base|br|col|embed|hr|img|input|link|meta|param|source|track|wbr)\b/i.test(x)&&!/<\/[^>]+>$/.test(x))depth++}return out.join('\n')}
function prettyCss(s){let out='',depth=0,token='';const flush=()=>{const x=token.trim();if(x)out+='  '.repeat(depth)+x;token=''};for(const c of s){if(c==='{'){flush();out+=' {\n';depth++}else if(c==='}'){flush();out+='\n';depth=Math.max(0,depth-1);out+='  '.repeat(depth)+'}\n'}else if(c===';'){token+=c;flush();out+='\n'}else token+=c}flush();return out.trim()}
function prettySql(s){let x=s.replace(/\s+/g,' ').trim();const kws=['SELECT','FROM','WHERE','GROUP BY','ORDER BY','HAVING','LIMIT','OFFSET','VALUES','SET','RETURNING','UNION','EXCEPT','INTERSECT','LEFT JOIN','RIGHT JOIN','INNER JOIN','FULL JOIN','CROSS JOIN','JOIN','ON','WITH','INSERT INTO','UPDATE','DELETE FROM','CREATE TABLE','ALTER TABLE'];for(const k of kws)x=x.replace(new RegExp(`\\s+${k.replace(' ','\\s+')}\\s+`,'ig'),`\n${k} `);x=x.replace(/\s+(AND|OR)\s+/ig,'\n  $1 ');return x.replace(/^\n/,'')}
function parseDelimited(s,sep){const rows=[];for(const line of s.split(/\r?\n/)){let row=[],cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===sep&&!q){row.push(cur);cur=''}else cur+=c}row.push(cur);rows.push(row)}return rows}
function aligned(rows){const widths=[];rows.forEach(r=>r.forEach((v,i)=>widths[i]=Math.min(60,Math.max(widths[i]||0,String(v).length))));return rows.map(r=>r.map((v,i)=>String(v).slice(0,60).padEnd(widths[i])).join('  |  ')).join('\n')}
function prettyUrl(s){const u=new URL(s.trim());const entries=[...u.searchParams.entries()];return [`${u.protocol}//${u.host}${u.pathname}`,entries.length?'Query parameters:':'',...entries.map(([k,v])=>`  ${k} = ${v}`),u.hash?`Hash: ${u.hash}`:''].filter(Boolean).join('\n')}
function prettyQuery(s){const p=new URLSearchParams(s.trim().replace(/^\?/,''));return[...p.entries()].map(([k,v])=>`${k} = ${v}`).join('\n')}
function prettyJwt(s){const [h,p,sig]=s.trim().split('.');return`HEADER\n${JSON.stringify(JSON.parse(b64decode(h,true)),null,2)}\n\nPAYLOAD\n${JSON.stringify(JSON.parse(b64decode(p,true)),null,2)}\n\nSIGNATURE\n${sig}\n\nNote: decoded only; signature is NOT verified.`}
function unescapeText(s){let x=s;try{const parsed=JSON.parse(`"${s.replace(/\\/g,'\\\\').replace(/"/g,'\\"')}"`);if(parsed!==s)x=parsed}catch{}try{if(/^"[\s\S]*"$/.test(s.trim())){const v=JSON.parse(s.trim());if(typeof v==='string')x=v}}catch{}return x.replace(/\\n/g,'\n').replace(/\\r/g,'\r').replace(/\\t/g,'\t').replace(/\\"/g,'"').replace(/\\\\/g,'\\')}
function prettyLog(s){return s.split(/\r?\n/).map(line=>line.replace(/^\s*/,'').replace(/\s+(INFO|WARN|ERROR|DEBUG|TRACE)\s+/i,'  $1  ')).join('\n')}
function format(s,type){switch(type){case'json':return JSON.stringify(JSON.parse(s),null,2);case'xml':case'html':return prettyMarkup(s);case'css':return prettyCss(s);case'sql':return prettySql(s);case'csv':return aligned(parseDelimited(s,','));case'tsv':return aligned(parseDelimited(s,'\t'));case'url':return prettyUrl(s);case'query':return prettyQuery(s);case'jwt':return prettyJwt(s);case'base64':{const d=b64decode(s,/[-_]/.test(s));const t=detect(d);return t==='json'?JSON.stringify(JSON.parse(d),null,2):d}case'escaped':{const d=unescapeText(s);const t=detect(d);return t!=='text'&&t!=='escaped'?format(d,t):d}case'log':return prettyLog(s);default:return s.replace(/\r\n/g,'\n').replace(/[ \t]+$/gm,'').replace(/\n{3,}/g,'\n\n')}}
function minify(s,type){switch(type){case'json':return JSON.stringify(JSON.parse(s));case'xml':case'html':return s.replace(/>\s+</g,'><').replace(/\s{2,}/g,' ').trim();case'css':return s.replace(/\/\*[\s\S]*?\*\//g,'').replace(/\s*([{}:;,])\s*/g,'$1').trim();case'sql':return s.replace(/\s+/g,' ').trim();case'url':return new URL(s.trim()).toString();case'query':return new URLSearchParams(s.trim().replace(/^\?/,'' )).toString();default:return s.replace(/\s+/g,' ').trim()}}
function selectedType(){const forced=$('type').value;return forced==='auto'?detect($('input').value):forced}
function run(mode='format'){const s=$('input').value,t=selectedType();$('detected').textContent=t.toUpperCase();try{$('output').value=mode==='minify'?minify(s,t):format(s,t);$('status').textContent=`${t.toUpperCase()} • ${s.length.toLocaleString()} input chars → ${$('output').value.length.toLocaleString()} output chars`;$('status').className='foot ok'}catch(e){$('output').value='';$('status').textContent=`Could not ${mode} as ${t}: ${e.message}`;$('status').className='foot error'}}
$('format').onclick=()=>run('format');$('minify').onclick=()=>run('minify');$('decode').onclick=()=>{const s=$('input').value,t=detect(s);try{$('output').value=t==='base64'?b64decode(s,/[-_]/.test(s)):t==='jwt'?prettyJwt(s):unescapeText(s);$('detected').textContent=t.toUpperCase()}catch(e){$('status').textContent=e.message}};$('paste').onclick=async()=>{$('input').value=await navigator.clipboard.readText();run()};$('copy').onclick=()=>navigator.clipboard.writeText($('output').value);$('swap').onclick=()=>{$('input').value=$('output').value;$('output').value='';run()};$('clear').onclick=()=>{$('input').value='';$('output').value='';$('detected').textContent='AUTO';$('status').textContent='Cleared.'};$('input').oninput=()=>{$('detected').textContent=detect($('input').value).toUpperCase()};
