(() => {
  if (window.__devBuddyLoaded) return;
  window.__devBuddyLoaded = true;
  const errors=[];
  window.addEventListener("error",e=>{errors.unshift({time:new Date().toLocaleTimeString(),type:"error",text:e.message,where:`${e.filename||""}:${e.lineno||""}`});errors.splice(100)});
  window.addEventListener("unhandledrejection",e=>{errors.unshift({time:new Date().toLocaleTimeString(),type:"promise",text:String(e.reason?.message||e.reason||"Unhandled rejection"),where:""});errors.splice(100)});

  const host=document.createElement("div");host.id="dev-buddy-host";document.documentElement.appendChild(host);const s=host.attachShadow({mode:"open"});
  s.innerHTML=`<style>*{box-sizing:border-box}#d{position:fixed;right:16px;top:16px;width:440px;max-width:calc(100vw - 20px);max-height:78vh;background:#08111f;color:#e2e8f0;z-index:2147483647;border:1px solid #334155;border-radius:14px;box-shadow:0 18px 55px #0009;font:12px ui-monospace,SFMono-Regular,Menlo,monospace;overflow:hidden}#bar{padding:9px;display:flex;gap:6px;align-items:center;cursor:move;background:#111827;border-bottom:1px solid #26354d}button{background:#263449;color:#fff;border:0;border-radius:7px;padding:6px 8px;cursor:pointer}button.on{background:#2563eb}#x{margin-left:auto;background:#7f1d1d}.tabs{display:flex;gap:4px;padding:7px;background:#0c1627;overflow:auto}.tabs button{white-space:nowrap}.out{padding:10px;overflow:auto;max-height:59vh;white-space:pre-wrap;word-break:break-word}.row{padding:7px 0;border-bottom:1px solid #1e293b}.k{color:#7dd3fc}.v{color:#e2e8f0}.muted{color:#94a3b8}.err{color:#fca5a5}.good{color:#86efac}input{width:100%;background:#0b1325;color:#fff;border:1px solid #334155;border-radius:7px;padding:7px;margin:4px 0}code{color:#fde68a}.hidden{display:none!important}</style>
  <section id="d"><div id="bar"><b>🛠 Dev Buddy</b><button id="inspect">Inspect</button><button id="copy">Copy</button><button id="x">×</button></div><div class="tabs"><button data-tab="element" class="on">Element</button><button data-tab="page">Page</button><button data-tab="storage">Storage</button><button data-tab="links">Links</button><button data-tab="images">Images</button><button data-tab="errors">Errors</button></div><div id="out" class="out">Click <b>Inspect</b>, then point at an element.</div></section>`;

  const panel=s.querySelector("#d"),out=s.querySelector("#out"),inspectBtn=s.querySelector("#inspect");let inspecting=false,last=null,lastText="";
  const safe=v=>String(v??"").slice(0,4000);
  const selector=el=>{if(!el)return"";if(el.id)return`${el.tagName.toLowerCase()}#${CSS.escape(el.id)}`;let p=el.tagName.toLowerCase();const cls=[...el.classList].slice(0,3);if(cls.length)p+=cls.map(x=>`.${CSS.escape(x)}`).join("");return p};
  function setOut(text){lastText=typeof text==="string"?text:"";out.textContent=text}
  function inspect(el){const cs=getComputedStyle(el),r=el.getBoundingClientRect(),attrs=[...el.attributes].map(a=>`${a.name}="${a.value}"`).join(" ");const text=`Selector: ${selector(el)}\nTag: ${el.tagName.toLowerCase()}\nAttributes: ${attrs||"—"}\nSize: ${Math.round(r.width)} × ${Math.round(r.height)}\nViewport position: ${Math.round(r.left)}, ${Math.round(r.top)}\n\nComputed CSS\nDisplay: ${cs.display}\nPosition: ${cs.position}\nz-index: ${cs.zIndex}\nFont: ${cs.fontFamily} / ${cs.fontSize} / ${cs.fontWeight}\nColor: ${cs.color}\nBackground: ${cs.backgroundColor}\nMargin: ${cs.margin}\nPadding: ${cs.padding}\nBorder: ${cs.border}\nFlex: ${cs.flex}\nGrid: ${cs.gridTemplateColumns}\nOverflow: ${cs.overflow}\n\nText\n${safe(el.innerText||el.textContent)}`;setOut(text)}
  function clearHighlight(){if(last){last.style.removeProperty("outline");last.style.removeProperty("outline-offset")}last=null}
  function onMove(e){if(!inspecting)return;const el=e.composedPath().find(x=>x instanceof Element&&x!==host&&!host.contains(x));if(!el||el===last)return;clearHighlight();last=el;el.style.setProperty("outline","3px solid #38bdf8","important");el.style.setProperty("outline-offset","2px","important");inspect(el)}
  document.addEventListener("mousemove",onMove,true);
  document.addEventListener("click",e=>{if(!inspecting)return;e.preventDefault();e.stopPropagation();inspecting=false;inspectBtn.classList.remove("on");if(last)inspect(last)},true);
  inspectBtn.onclick=()=>{inspecting=!inspecting;inspectBtn.classList.toggle("on",inspecting);if(!inspecting)clearHighlight()};

  const renderers={
    page(){setOut(`URL: ${location.href}\nTitle: ${document.title}\nOrigin: ${location.origin}\nViewport: ${innerWidth} × ${innerHeight}\nDevice pixel ratio: ${devicePixelRatio}\nDocument: ${document.documentElement.scrollWidth} × ${document.documentElement.scrollHeight}\nDOM elements: ${document.querySelectorAll("*").length}\nLinks: ${document.links.length}\nImages: ${document.images.length}\nScripts: ${document.scripts.length}\nStylesheets: ${document.styleSheets.length}\niframes: ${document.querySelectorAll("iframe").length}\nLocalStorage keys: ${localStorage.length}\nSessionStorage keys: ${sessionStorage.length}\nCookies visible to JS: ${document.cookie?document.cookie.split(";").length:0}\nReady state: ${document.readyState}\nLanguage: ${document.documentElement.lang||navigator.language}`)},
    storage(){let rows=[];rows.push("LOCAL STORAGE");for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);rows.push(`${k} = ${safe(localStorage.getItem(k))}`)}rows.push("\nSESSION STORAGE");for(let i=0;i<sessionStorage.length;i++){const k=sessionStorage.key(i);rows.push(`${k} = ${safe(sessionStorage.getItem(k))}`)}rows.push("\nCOOKIES (JS-visible only)",document.cookie||"—");setOut(rows.join("\n"))},
    links(){setOut([...document.links].slice(0,200).map((a,i)=>`${i+1}. ${safe(a.innerText).trim()||"(no text)"}\n   ${a.href}`).join("\n")||"No links found.")},
    images(){setOut([...document.images].slice(0,200).map((a,i)=>`${i+1}. ${a.naturalWidth}×${a.naturalHeight} ${a.alt?`alt="${a.alt}"`:""}\n   ${a.currentSrc||a.src}`).join("\n")||"No images found.")},
    errors(){setOut(errors.length?errors.map(x=>`[${x.time}] ${x.type.toUpperCase()} ${x.text}${x.where?`\n  ${x.where}`:""}`).join("\n\n"):"No captured window errors since this page load.")}
  };
  s.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{s.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("on",x===b));const tab=b.dataset.tab;if(tab==="element"){if(last)inspect(last);else setOut("Click Inspect, then point at an element.")}else renderers[tab]?.()});
  s.querySelector("#copy").onclick=async()=>{try{await navigator.clipboard.writeText(lastText||out.innerText);s.querySelector("#copy").textContent="Copied ✓";setTimeout(()=>s.querySelector("#copy").textContent="Copy",800)}catch{}};
  s.querySelector("#x").onclick=()=>{panel.classList.add("hidden");inspecting=false;inspectBtn.classList.remove("on");clearHighlight()};
  chrome.runtime.onMessage.addListener(m=>{if(m?.type!=="DEV_TOGGLE")return;panel.classList.toggle("hidden")});
  let drag=null,bar=s.querySelector("#bar");bar.onpointerdown=e=>{if(e.target.tagName==="BUTTON")return;const r=panel.getBoundingClientRect();drag=[e.clientX-r.left,e.clientY-r.top];panel.style.right="auto";bar.setPointerCapture(e.pointerId)};bar.onpointermove=e=>{if(!drag)return;panel.style.left=`${Math.max(0,Math.min(innerWidth-panel.offsetWidth,e.clientX-drag[0]))}px`;panel.style.top=`${Math.max(0,Math.min(innerHeight-panel.offsetHeight,e.clientY-drag[1]))}px`};bar.onpointerup=()=>drag=null;
})();
