(()=>{
 if(window.__bgaDevBuddyLoaded)return;window.__bgaDevBuddyLoaded=true;
 let globals={},errors=[];
 window.addEventListener('message',e=>{if(e.source===window&&e.data?.source==='bga-dev-buddy-probe'&&e.data.type==='BGA_GLOBALS')globals=e.data.globals||{}});
 window.addEventListener('error',e=>{errors.unshift({type:'error',message:e.message,file:e.filename,line:e.lineno,col:e.colno,at:Date.now()});errors=errors.slice(0,50)},true);
 window.addEventListener('unhandledrejection',e=>{errors.unshift({type:'promise',message:String(e.reason?.message||e.reason||'Unhandled rejection'),at:Date.now()});errors=errors.slice(0,50)});
 const uniq=a=>[...new Set(a.filter(Boolean))];
 function ids(){const u=new URL(location.href),q=Object.fromEntries(u.searchParams.entries()),path=location.pathname;const out={game:q.game||q.gamename||q.game_name||null,gameId:q.game_id||q.gameid||null,tableId:q.table||q.table_id||q.tableid||null,playerId:q.player||q.player_id||q.playerid||null,studioId:q.project||q.project_id||null};const patterns=[[/\/table\/(\d+)/,'tableId'],[/\/player\/(\d+)/,'playerId'],[/\/gamepanel[^/]*$/,'game']];for(const[p,k]of patterns){const m=path.match(p);if(m?.[1])out[k]||=m[1]}for(const el of document.querySelectorAll('[data-game-id],[data-table-id],[data-player-id],input[name="game"],input[name="table"],input[name="table_id"]')){out.gameId||=el.dataset?.gameId;out.tableId||=el.dataset?.tableId||((el.name==='table'||el.name==='table_id')?el.value:null);out.playerId||=el.dataset?.playerId;out.game||=(el.name==='game'?el.value:null)}out.game||=globals?.gameui?.game_name;out.tableId||=globals?.gameui?.table_id;out.playerId||=globals?.gameui?.player_id;return out}
 function scan(){window.postMessage({source:'bga-dev-buddy-control',type:'PROBE'},'*');const found=ids(),scripts=[...document.scripts].map(s=>s.src).filter(Boolean),styles=[...document.querySelectorAll('link[rel="stylesheet"]')].map(x=>x.href).filter(Boolean),images=[...document.images].map(x=>x.currentSrc||x.src).filter(Boolean);const links=[...document.links].map(a=>a.href).filter(h=>/boardgamearena\.com/i.test(h));const localKeys=[];try{for(let i=0;i<localStorage.length;i++)localKeys.push(localStorage.key(i))}catch{}return{host:location.host,url:location.href,title:document.title,isStudio:location.host.startsWith('studio.'),ids:found,globals,assets:{scripts:uniq(scripts).slice(0,100),styles:uniq(styles).slice(0,100),images:uniq(images).slice(0,120)},links:uniq(links).slice(0,150),storageKeys:localKeys.filter(k=>/bga|game|table|player|studio/i.test(k)).slice(0,60),errors:[...errors]}}
 chrome.runtime.onMessage.addListener((m,_s,send)=>{if(m.type==='BGA_SCAN'){setTimeout(()=>send({ok:true,data:scan()}),60);return true}if(m.type==='BGA_ERRORS_CLEAR'){errors=[];send({ok:true});return false}return false});
})();
