(() => {
  if (window.__dataGrabberLoaded) return;
  window.__dataGrabberLoaded = true;
  let candidates=[];
  const text = el => (el?.innerText || el?.textContent || '').replace(/\s+/g,' ').trim();
  const clean = s => String(s ?? '').replace(/\s+/g,' ').trim();
  function cssPath(el){if(!el||el===document.body)return'body';const parts=[];let n=el;while(n&&n.nodeType===1&&n!==document.body&&parts.length<6){let p=n.tagName.toLowerCase();if(n.id){parts.unshift(`#${CSS.escape(n.id)}`);break}const cls=[...n.classList].filter(Boolean).slice(0,2);if(cls.length)p+='.'+cls.map(CSS.escape).join('.');const siblings=n.parentElement?[...n.parentElement.children].filter(x=>x.tagName===n.tagName):[];if(siblings.length>1)p+=`:nth-of-type(${siblings.indexOf(n)+1})`;parts.unshift(p);n=n.parentElement}return ['body',...parts].join(' > ')}
  function tableCandidate(table,index){const rows=[...table.rows];if(rows.length<2)return null;let headers=[...rows[0].cells].map((c,i)=>clean(c.innerText)||`column_${i+1}`);let start=1;const th=[...table.querySelectorAll('thead th')];if(th.length){headers=th.map((c,i)=>clean(c.innerText)||`column_${i+1}`);start=table.tHead?.rows?.length||1}const data=rows.slice(start).map(r=>Object.fromEntries([...r.cells].map((c,i)=>[headers[i]||`column_${i+1}`,clean(c.innerText)]))).filter(r=>Object.values(r).some(Boolean));return{id:`table:${index}`,type:'table',label:`Table ${index+1} • ${data.length} rows × ${headers.length} cols`,selector:cssPath(table),headers,rows:data}}
  function meaningfulChildren(el){const direct=[...el.children].filter(c=>clean(c.innerText));if(!direct.length)return[];return direct.slice(0,12)}
  function cardRow(el){const row={};const links=[...el.querySelectorAll('a[href]')].slice(0,3);const imgs=[...el.querySelectorAll('img[src]')].slice(0,2);const bits=[];meaningfulChildren(el).forEach(c=>{const v=clean(c.innerText);if(v&&v.length<400)bits.push(v)});if(!bits.length){const v=clean(el.innerText);if(v)bits.push(v)}bits.slice(0,8).forEach((v,i)=>row[`field_${i+1}`]=v);if(links[0])row.link=links[0].href;if(imgs[0])row.image=imgs[0].currentSrc||imgs[0].src;return row}
  function repeatedCandidates(){const out=[];const parents=[...document.querySelectorAll('main,section,article,div,ul,ol')].slice(0,2500);for(const p of parents){const children=[...p.children];if(children.length<3||children.length>250)continue;const groups=new Map();for(const c of children){const key=`${c.tagName}.${[...c.classList].slice(0,2).sort().join('.')}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(c)}for(const [key,arr] of groups){if(arr.length<3)continue;const sample=arr.slice(0,5).map(text).filter(Boolean);if(sample.length<3)continue;const avg=sample.reduce((n,s)=>n+s.length,0)/sample.length;if(avg<3||avg>1200)continue;const rows=arr.map(cardRow).filter(r=>Object.keys(r).length);if(rows.length<3)continue;out.push({type:'repeated',label:`Repeated ${key} • ${rows.length} items`,selector:cssPath(p),childKey:key,rows});if(out.length>=12)return out}}return out}
  function detect(){const tables=[...document.querySelectorAll('table')].map(tableCandidate).filter(Boolean);const repeats=repeatedCandidates().map((x,i)=>({...x,id:`repeat:${i}`}));candidates=[...tables,...repeats].sort((a,b)=>b.rows.length-a.rows.length).slice(0,20);return candidates.map(({rows,...c})=>({...c,rowCount:rows.length,preview:rows.slice(0,3)}))}
  function refreshCandidate(id){const c=candidates.find(x=>x.id===id);if(!c)return null;if(c.type==='table'){const el=document.querySelector(c.selector);if(!el)return c;const fresh=tableCandidate(el,0);if(fresh){c.rows=fresh.rows;c.headers=fresh.headers}}else{const p=document.querySelector(c.selector);if(p){let nodes=[...p.children];const [tag,...classes]=c.childKey.split('.');nodes=nodes.filter(n=>n.tagName===tag&&classes.every(k=>n.classList.contains(k)));c.rows=nodes.map(cardRow).filter(r=>Object.keys(r).length)}}return c}
  function findMoreButton(){const all=[...document.querySelectorAll('button,a,[role="button"]')].filter(el=>{const r=el.getBoundingClientRect();return r.width>0&&r.height>0});const score=el=>{const t=clean(el.innerText||el.getAttribute('aria-label')).toLowerCase();if(/load more|show more|see more|more results|view more/.test(t))return 100;if(/next page|next results/.test(t))return 80;if(/^next\b|^›$|^»$/.test(t))return 60;return 0};return all.map(el=>({el,s:score(el)})).filter(x=>x.s).sort((a,b)=>b.s-a.s)[0]?.el||null}
  const wait=ms=>new Promise(r=>setTimeout(r,ms));
  async function autoCollect(id,maxSteps=8){const c=refreshCandidate(id);if(!c)return{error:'Dataset no longer exists.'};const seen=new Set(c.rows.map(r=>JSON.stringify(r))),rows=[...c.rows];let clicks=0,lastCount=rows.length;for(let i=0;i<maxSteps;i++){const btn=findMoreButton();if(!btn)break;if(btn.tagName==='A'&&btn.href&&new URL(btn.href,location.href).href!==location.href){return{rows,clicks,nextUrl:btn.href,note:'Navigation pagination detected. Current rows collected; open next page and use Add Current Page to continue the same session.'}}btn.scrollIntoView({block:'center'});btn.click();clicks++;await wait(1200);const fresh=refreshCandidate(id);for(const r of fresh?.rows||[]){const k=JSON.stringify(r);if(!seen.has(k)){seen.add(k);rows.push(r)}}if(rows.length===lastCount){await wait(1000);const fresh2=refreshCandidate(id);for(const r of fresh2?.rows||[]){const k=JSON.stringify(r);if(!seen.has(k)){seen.add(k);rows.push(r)}}if(rows.length===lastCount)break}lastCount=rows.length}return{rows,clicks,nextUrl:null}}
  chrome.runtime.onMessage.addListener((m,_s,send)=>{(async()=>{if(m.type==='DG_DETECT')return send({ok:true,candidates:detect(),url:location.href,title:document.title});if(m.type==='DG_ROWS'){const c=refreshCandidate(m.id);return send({ok:!!c,rows:c?.rows||[]})}if(m.type==='DG_AUTO')return send({ok:true,...await autoCollect(m.id,Number(m.maxSteps)||8)});if(m.type==='DG_NEXT'){const b=findMoreButton();return send({ok:true,next:b?.tagName==='A'?b.href:null,label:b?clean(b.innerText||b.getAttribute('aria-label')):''})}return send({ok:false})})().catch(e=>send({ok:false,error:e.message}));return true});
})();
