const $=id=>document.getElementById(id), SESSION='dataGrabberSession';let tabId=null,candidates=[],rows=[];
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
async function active(){const[t]=await chrome.tabs.query({active:true,currentWindow:true});tabId=t?.id;return t}
async function msg(m){if(!tabId)await active();return chrome.tabs.sendMessage(tabId,m)}
function notice(t,kind=''){const n=$('notice');n.textContent=t;n.className=kind}
function dedupe(input){const s=new Set(),out=[];for(const r of input){const k=JSON.stringify(r);if(!s.has(k)){s.add(k);out.push(r)}}return out}
async function save(){await chrome.storage.local.set({[SESSION]:rows});renderRows()}
function keysFor(data){return[...new Set(data.slice(0,500).flatMap(r=>r&&typeof r==='object'&&!Array.isArray(r)?Object.keys(r):[]))]}
function renderRows(data=rows){$('count').textContent=`${rows.length.toLocaleString()} rows collected`;const show=data.slice(0,200);if(!show.length){$('previewBox').innerHTML='<div class="empty">No rows collected yet.</div>';return}const keys=keysFor(show);$('previewBox').innerHTML=`<table><thead><tr>${keys.map(k=>`<th>${esc(k)}</th>`).join('')}</tr></thead><tbody>${show.map(r=>`<tr>${keys.map(k=>`<td>${esc(typeof r[k]==='object'?JSON.stringify(r[k]):r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table>${data.length>200?`<div class="card">Preview limited to 200 of ${data.length} rows.</div>`:''}`}
function selected(){return candidates.find(c=>c.id===$('dataset').value)}
async function detect(){notice('Scanning page…');const r=await msg({type:'DG_DETECT'});if(!r?.ok)throw new Error(r?.error||'Could not inspect this page.');candidates=r.candidates||[];$('dataset').innerHTML=candidates.length?candidates.map(c=>`<option value="${esc(c.id)}">${esc(c.label)}</option>`).join(''):'<option>No table-like data detected</option>';$('source').textContent=r.title?`${r.title}`:'';notice(candidates.length?`${candidates.length} dataset candidate${candidates.length===1?'':'s'} detected.`:'No strong dataset candidates detected.',candidates.length?'ok':'error');if(candidates[0])previewCandidate()}
function previewCandidate(){const c=selected();if(!c)return;renderRows(c.preview||[]);$('count').textContent=`Preview • ${c.rowCount} detected rows`}
async function addCurrent(){const c=selected();if(!c)return;notice('Collecting current page…');const r=await msg({type:'DG_ROWS',id:c.id});if(!r?.ok)throw new Error('Dataset is no longer available. Detect again.');const before=rows.length;rows=dedupe([...rows,...r.rows]);await save();notice(`Added ${rows.length-before} new rows; ${rows.length} unique total.`,'ok')}
async function autoMore(){const c=selected();if(!c)return;notice('Clicking same-page Load/See More controls and collecting new rows…');const r=await msg({type:'DG_AUTO',id:c.id,maxSteps:+$('steps').value});if(!r?.ok)throw new Error(r?.error||'Auto collection failed.');const before=rows.length;rows=dedupe([...rows,...(r.rows||[])]);await save();let t=`${r.clicks||0} expansion click(s); added ${rows.length-before} rows.`;if(r.nextUrl)t+=` Navigation pagination detected: ${r.nextUrl}. Open it, then use Add Current Page to continue the same collection.`;notice(t,'ok')}
function csv(data){const keys=keysFor(data),q=v=>{const s=typeof v==='object'?JSON.stringify(v):String(v??'');return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s};return[keys.map(q).join(','),...data.map(r=>keys.map(k=>q(r[k])).join(','))].join('\n')}
function md(data){const keys=keysFor(data),cell=v=>String(typeof v==='object'?JSON.stringify(v):v??'').replaceAll('|','\\|').replace(/\r?\n/g,' ');return`| ${keys.join(' | ')} |\n| ${keys.map(()=> '---').join(' | ')} |\n`+data.map(r=>`| ${keys.map(k=>cell(r[k])).join(' | ')} |`).join('\n')}
function download(name,text,type){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
$('detect').onclick=()=>detect().catch(e=>notice(e.message,'error'));$('preview').onclick=previewCandidate;$('add').onclick=()=>addCurrent().catch(e=>notice(e.message,'error'));$('auto').onclick=()=>autoMore().catch(e=>notice(e.message,'error'));$('clear').onclick=async()=>{rows=[];await save();notice('Collection cleared.')};$('copy').onclick=async()=>{await navigator.clipboard.writeText(JSON.stringify(rows,null,2));notice('JSON copied.','ok')};$('exportCsv').onclick=()=>download('grabbed-data.csv',csv(rows),'text/csv');$('exportJson').onclick=()=>download('grabbed-data.json',JSON.stringify(rows,null,2),'application/json');$('exportMd').onclick=()=>download('grabbed-data.md',md(rows),'text/markdown');$('dataset').onchange=previewCandidate;
(async()=>{await active();({[SESSION]:rows=[]}=await chrome.storage.local.get(SESSION));renderRows();detect().catch(()=>notice('Refresh the page after installing/reloading this extension.','error'))})();
