const BRIDGE='https://ios-apps-beta.vercel.app/api/bga';
const MAX_RAW=3*1024*1024;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={connected:false,path:'',items:[],sftpSelected:null,editorSource:null,editorPath:'',editorBytes:null,ghToken:'',ghRepo:'',ghPath:'',ghItems:[],ghSelected:null};
function setStatus(id,text,kind=''){const el=$(id);el.textContent=text||'';el.className='status'+(kind?` ${kind}`:'')}
function fmtBytes(n=0){if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;return`${(n/1048576).toFixed(1)} MB`}
function norm(p=''){return String(p).replace(/\\/g,'/').split('/').filter(x=>x&&x!=='.').join('/')}
function parent(p=''){const a=norm(p).split('/').filter(Boolean);a.pop();return a.join('/')}
function join(a,b){return [norm(a),String(b||'').replace(/^\/+|\/+$/g,'')].filter(Boolean).join('/')}
function basename(p=''){return norm(p).split('/').pop()||''}
function bytesToB64(bytes){let bin='';for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(bin)}
function b64ToBytes(s){const bin=atob(s||''),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
function textBytes(text){return new TextEncoder().encode(text)}
function bytesText(bytes){return new TextDecoder('utf-8',{fatal:false}).decode(bytes)}
function assertSize(bytes){if(bytes.length>MAX_RAW)throw new Error(`Browser bridge transfer is limited to about ${fmtBytes(MAX_RAW)} per file to stay below the hosting platform payload ceiling.`)}
async function bridge(action,body={}){const user=$('sftpUser').value.trim();const pass=$('sftpPass').value;if(!user||!pass)throw new Error('Enter BGA Studio username and password.');const r=await fetch(BRIDGE,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},cache:'no-store',body:JSON.stringify({action,host:'1.studio.boardgamearena.com',port:2022,username:user,password:pass,...body})});let data;try{data=await r.json()}catch{throw new Error(`Bridge returned HTTP ${r.status} with a non-JSON response.`)}if(!r.ok||data.ok===false)throw new Error(data.error||`Bridge HTTP ${r.status}`);return data}
async function saveSession(){await chrome.storage.local.set({sftpBuddyUser:$('sftpUser').value.trim(),sftpBuddyPath:state.path});await chrome.storage.session.set({sftpBuddyPass:$('sftpPass').value,ghBuddyToken:state.ghToken})}
async function loadPrefs(){const l=await chrome.storage.local.get({sftpBuddyUser:'',sftpBuddyPath:''});const s=await chrome.storage.session.get({sftpBuddyPass:'',ghBuddyToken:''});$('sftpUser').value=l.sftpBuddyUser;$('sftpPass').value=s.sftpBuddyPass;state.path=l.sftpBuddyPath||'';$('path').value=state.path;state.ghToken=s.ghBuddyToken||'';$('ghToken').value=state.ghToken}
function connected(v,msg){state.connected=v;$('connBadge').textContent=v?'Connected':'Disconnected';$('connBadge').className='badge '+(v?'on':'');if(msg)setStatus('sftpStatus',msg,v?'good':'')}
async function connect(){setStatus('sftpStatus','Connecting…');try{const x=await bridge('health');connected(true,`Connected. Remote cwd: ${x.cwd||'.'}`);await saveSession();await loadSftp(state.path)}catch(e){connected(false);setStatus('sftpStatus',e.message,'bad')}}
function disconnect(){connected(false,'Disconnected.');$('sftpPass').value='';chrome.storage.session.remove('sftpBuddyPass');state.items=[];renderSftp()}
async function loadSftp(path=state.path){if(!state.connected)throw new Error('Connect first.');state.path=norm(path);$('path').value=state.path;setStatus('sftpStatus',`Loading ${state.path||'.'}…`);const x=await bridge('list',{path:state.path});state.items=(x.items||[]).sort((a,b)=>(a.type==='dir'?0:1)-(b.type==='dir'?0:1)||a.name.localeCompare(b.name));await saveSession();renderSftp();setStatus('sftpStatus',`${state.items.length} item${state.items.length===1?'':'s'} in ${state.path||'.'}`,'good')}
function renderSftp(){const q=$('filter').value.trim().toLowerCase();const rows=state.items.filter(x=>!q||x.name.toLowerCase().includes(q));$('fileList').innerHTML=rows.map(x=>`<div class="file ${state.sftpSelected?.path===x.path?'selected':''}" data-path="${esc(x.path)}"><div class="icon">${x.type==='dir'?'📁':'📄'}</div><div class="name"><b>${esc(x.name)}</b><small>${x.type==='dir'?'Folder':fmtBytes(x.size)}${x.modified?` • ${new Date(x.modified).toLocaleString()}`:''}</small></div><div class="actions">${x.type==='file'?'<button data-act="open">Open</button><button data-act="down">↓</button>':''}<button data-act="rename">Rename</button><button data-act="dup">Copy</button><button data-act="trash">Trash</button><button data-act="delete">Delete</button></div></div>`).join('')||'<div class="file"><div></div><div class="name"><b>No matching items</b></div><div></div></div>';
 document.querySelectorAll('#fileList .file[data-path]').forEach(el=>{const item=state.items.find(x=>x.path===el.dataset.path);el.onclick=e=>{if(e.target.closest('button'))return;state.sftpSelected=item;renderSftp();updateSyncLabels()};el.ondblclick=()=>item.type==='dir'?loadSftp(item.path).catch(err=>setStatus('sftpStatus',err.message,'bad')):openSftp(item).catch(err=>setStatus('sftpStatus',err.message,'bad'));el.querySelectorAll('button').forEach(b=>b.onclick=e=>{e.stopPropagation();const a=b.dataset.act;if(a==='open')openSftp(item).catch(showSftpErr);if(a==='down')downloadSftp(item).catch(showSftpErr);if(a==='rename')renameSftp(item).catch(showSftpErr);if(a==='dup')duplicateSftp(item).catch(showSftpErr);if(a==='trash')trashSftp(item).catch(showSftpErr);if(a==='delete')permanentDelete(item).catch(showSftpErr)})})}
function showSftpErr(e){setStatus('sftpStatus',e.message,'bad')}
async function readSftp(item){const x=await bridge('read',{path:item.path});const bytes=b64ToBytes(x.base64);assertSize(bytes);return bytes}
async function openSftp(item){const bytes=await readSftp(item);state.sftpSelected=item;state.editorSource='sftp';state.editorPath=item.path;state.editorBytes=bytes;$('editor').value=bytesText(bytes);$('editPath').textContent=item.path;$('editMeta').textContent=fmtBytes(bytes.length);$('syncSftpDest').value=item.path;updateSyncLabels();switchTab('editor');setStatus('editorStatus','Loaded from SFTP.','good')}
async function downloadSftp(item){const bytes=await readSftp(item),blob=new Blob([bytes]),url=URL.createObjectURL(blob);await chrome.downloads.download({url,filename:basename(item.path)||'download',saveAs:true});setTimeout(()=>URL.revokeObjectURL(url),5000)}
async function writeSftp(path,bytes,{backup=false}={}){assertSize(bytes);path=norm(path);if(!path)throw new Error('Destination path required.');if(backup){try{const old=await bridge('read',{path});const stamp=new Date().toISOString().replace(/[:.]/g,'-');await bridge('write',{path:`${path}.bak-${stamp}`,base64:old.base64})}catch(e){if(!/not found|no such|ENOENT/i.test(e.message))throw e}}await bridge('write',{path,base64:bytesToB64(bytes)});return path}
async function renameSftp(item){const to=prompt('Rename/move to:',item.path);if(!to||norm(to)===item.path)return;await bridge('rename',{from:item.path,to:norm(to)});await loadSftp(state.path)}
async function duplicateSftp(item){const to=prompt('Copy to:',join(parent(item.path),basename(item.path)+'-copy'));if(!to)return;async function cp(src,dst){if(src.type==='dir'){await bridge('mkdir',{path:dst});const list=(await bridge('list',{path:src.path})).items||[];for(const child of list)await cp(child,join(dst,child.name))}else{const bytes=await readSftp(src);await writeSftp(dst,bytes,{})}}await cp(item,norm(to));await loadSftp(state.path)}
async function trashSftp(item){if(!confirm(`Move ${item.name} to .sftp-trash?\n\nCancel lets you keep it.`))return;try{await bridge('mkdir',{path:'.sftp-trash'})}catch{}const stamp=new Date().toISOString().replace(/[:.]/g,'-'),dest=join('.sftp-trash',`${basename(item.path)}-${stamp}`);await bridge('rename',{from:item.path,to:dest});await loadSftp(state.path)}
async function permanentDelete(item){if(!confirm(`PERMANENTLY delete ${item.path}? This cannot be undone.`))return;await bridge('delete',{path:item.path,recursive:true});await loadSftp(state.path)}
async function createFolder(){const name=prompt('New folder name:');if(!name)return;await bridge('mkdir',{path:join(state.path,name)});await loadSftp(state.path)}
async function createFile(){const name=prompt('New file name:');if(!name)return;const path=join(state.path,name);await writeSftp(path,new Uint8Array(),{});await loadSftp(state.path);const item=state.items.find(x=>x.path===path)||{path,name,type:'file',size:0};await openSftp(item)}
async function uploadFile(file){if(!file)return;const bytes=new Uint8Array(await file.arrayBuffer());assertSize(bytes);await writeSftp(join(state.path,file.name),bytes,{});await loadSftp(state.path)}
async function saveEditorSftp(){let path=state.editorSource==='sftp'?state.editorPath:$('syncSftpDest').value.trim();if(!path)path=prompt('SFTP destination path:',state.editorPath||join(state.path,'file.txt'));if(!path)return;try{await writeSftp(path,textBytes($('editor').value),{backup:$('backupBeforeSave').checked});state.editorSource='sftp';state.editorPath=norm(path);$('editPath').textContent=state.editorPath;setStatus('editorStatus','Saved to SFTP.','good');await loadSftp(parent(state.editorPath))}catch(e){setStatus('editorStatus',e.message,'bad')}}

async function ghFetch(path='',opts={}){if(!state.ghToken)throw new Error('Enter/connect a GitHub token first.');const url=path.startsWith('http')?path:`https://api.github.com${path}`;const r=await fetch(url,{...opts,headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',Authorization:`Bearer ${state.ghToken}`,...(opts.headers||{})}});let data=null;try{data=await r.json()}catch{}if(!r.ok)throw new Error(data?.message||`GitHub HTTP ${r.status}`);return data}
async function loadRepos(){state.ghToken=$('ghToken').value.trim();if(!state.ghToken)throw new Error('GitHub token required.');await chrome.storage.session.set({ghBuddyToken:state.ghToken});setStatus('ghStatus','Loading repositories…');let repos=await ghFetch('/user/repos?per_page=100&sort=updated&affiliation=owner,collaborator,organization_member');$('ghRepo').innerHTML='<option value="">Choose repository…</option>'+repos.map(r=>`<option value="${esc(r.full_name)}">${esc(r.full_name)}</option>`).join('');setStatus('ghStatus',`${repos.length} repositories loaded.`,'good')}
async function loadGh(path=state.ghPath){if(!state.ghRepo)throw new Error('Choose a GitHub repository.');state.ghPath=norm(path);$('ghPath').value=state.ghPath;setStatus('ghStatus',`Loading ${state.ghPath||'/'}…`);const encoded=state.ghPath.split('/').filter(Boolean).map(encodeURIComponent).join('/');const endpoint=encoded?`/repos/${state.ghRepo}/contents/${encoded}`:`/repos/${state.ghRepo}/contents/`;const x=await ghFetch(endpoint);state.ghItems=Array.isArray(x)?x:[x];renderGh();setStatus('ghStatus',`${state.ghItems.length} item${state.ghItems.length===1?'':'s'}.`,'good')}
function renderGh(){$('ghList').innerHTML=state.ghItems.map(x=>`<div class="file ${state.ghSelected?.path===x.path?'selected':''}" data-gh="${esc(x.path)}"><div class="icon">${x.type==='dir'?'📁':'📄'}</div><div class="name"><b>${esc(x.name)}</b><small>${x.type}${x.size!=null?` • ${fmtBytes(x.size)}`:''}</small></div><div class="actions">${x.type==='file'?'<button data-act="open">Open</button>':''}</div></div>`).join('')||'<div class="file"><div></div><div class="name"><b>Empty folder</b></div><div></div></div>';document.querySelectorAll('[data-gh]').forEach(el=>{const item=state.ghItems.find(x=>x.path===el.dataset.gh);el.onclick=e=>{if(e.target.closest('button'))return;state.ghSelected=item;renderGh();$('syncGhDest').value=item.path;updateSyncLabels()};el.ondblclick=()=>item.type==='dir'?loadGh(item.path).catch(showGhErr):openGh(item).catch(showGhErr);el.querySelector('[data-act="open"]')?.addEventListener('click',e=>{e.stopPropagation();openGh(item).catch(showGhErr)})})}
function showGhErr(e){setStatus('ghStatus',e.message,'bad')}
async function ghFile(item){const x=await ghFetch(`/repos/${state.ghRepo}/contents/${item.path.split('/').map(encodeURIComponent).join('/')}`);if(!x.content)throw new Error('GitHub did not return inline file content. Large/binary files are not supported by this editor.');return {...x,bytes:b64ToBytes(x.content.replace(/\s/g,''))}}
async function openGh(item){const x=await ghFile(item);assertSize(x.bytes);state.ghSelected=x;state.editorSource='github';state.editorPath=x.path;state.editorBytes=x.bytes;$('editor').value=bytesText(x.bytes);$('editPath').textContent=`${state.ghRepo}:${x.path}`;$('editMeta').textContent=fmtBytes(x.bytes.length);$('syncGhDest').value=x.path;updateSyncLabels();switchTab('editor');setStatus('editorStatus','Loaded from GitHub.','good')}
async function putGh(path,bytes,message,sha=null){assertSize(bytes);if(!state.ghRepo)throw new Error('Choose a GitHub repository.');const body={message:message||'Update from SFTP Buddy Browser',content:bytesToB64(bytes)};if(sha)body.sha=sha;return ghFetch(`/repos/${state.ghRepo}/contents/${norm(path).split('/').map(encodeURIComponent).join('/')}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
async function findGhSha(path){try{const x=await ghFetch(`/repos/${state.ghRepo}/contents/${norm(path).split('/').map(encodeURIComponent).join('/')}`);return x.sha||null}catch(e){if(/Not Found/i.test(e.message))return null;throw e}}
async function saveEditorGh(){let path=state.editorSource==='github'?state.editorPath:$('syncGhDest').value.trim();if(!path)path=prompt('GitHub destination path:',state.editorPath||'file.txt');if(!path)return;try{const sha=await findGhSha(path);await putGh(path,textBytes($('editor').value),$('syncMessage').value,sha);state.editorSource='github';state.editorPath=norm(path);setStatus('editorStatus','Committed to GitHub.','good');await loadGh(parent(state.editorPath))}catch(e){setStatus('editorStatus',e.message,'bad')}}
async function deleteGh(){const x=state.ghSelected;if(!x||x.type==='dir')throw new Error('Select a GitHub file first.');if(!confirm(`Delete ${x.path} from ${state.ghRepo} with a commit?`))return;const full=x.sha?x:await ghFile(x);await ghFetch(`/repos/${state.ghRepo}/contents/${x.path.split('/').map(encodeURIComponent).join('/')}`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`Delete ${x.path} from SFTP Buddy Browser`,sha:full.sha})});state.ghSelected=null;await loadGh(state.ghPath)}

function updateSyncLabels(){$('syncSftp').textContent=state.sftpSelected?.path||'None';$('syncGithub').textContent=state.ghSelected?.path?(state.ghRepo+':'+state.ghSelected.path):'None'}
function simpleDiff(a,b){if(a===b)return'✓ Files are text-identical.';const A=a.split('\n'),B=b.split('\n'),out=[],n=Math.max(A.length,B.length);for(let i=0;i<n&&out.length<300;i++){if(A[i]===B[i])continue;if(A[i]!=null)out.push(`- ${i+1}: ${A[i]}`);if(B[i]!=null)out.push(`+ ${i+1}: ${B[i]}`)}if(n>300)out.push('…diff output capped…');return out.join('\n')||'Different binary/text decoding.'}
async function compareSelected(){try{if(!state.sftpSelected||state.sftpSelected.type==='dir'||!state.ghSelected||state.ghSelected.type==='dir')throw new Error('Select one file on each side first.');const [s,g]=await Promise.all([readSftp(state.sftpSelected),ghFile(state.ghSelected)]);$('diff').textContent=simpleDiff(bytesText(s),bytesText(g.bytes));setStatus('syncStatus',`${fmtBytes(s.length)} SFTP vs ${fmtBytes(g.bytes.length)} GitHub.`,'good')}catch(e){setStatus('syncStatus',e.message,'bad')}}
async function githubToSftp(){try{if(!state.ghSelected||state.ghSelected.type==='dir')throw new Error('Select a GitHub file first.');const g=await ghFile(state.ghSelected),dest=norm($('syncSftpDest').value||join(state.path,basename(g.path)));if(!dest)throw new Error('Enter an SFTP destination.');const existing=state.sftpSelected?.path===dest?await readSftp(state.sftpSelected).catch(()=>null):null;if(existing)$('diff').textContent=simpleDiff(bytesText(existing),bytesText(g.bytes));if(!confirm(`Write GitHub file to SFTP?\n\n${state.ghRepo}:${g.path}\n→ ${dest}`))return;await writeSftp(dest,g.bytes,{backup:true});setStatus('syncStatus',`GitHub → SFTP complete: ${dest}`,'good');await loadSftp(parent(dest))}catch(e){setStatus('syncStatus',e.message,'bad')}}
async function sftpToGithub(){try{if(!state.sftpSelected||state.sftpSelected.type==='dir')throw new Error('Select an SFTP file first.');const bytes=await readSftp(state.sftpSelected),dest=norm($('syncGhDest').value||state.sftpSelected.name);if(!dest)throw new Error('Enter a GitHub destination.');let sha=null,old=null;try{const g=await ghFetch(`/repos/${state.ghRepo}/contents/${dest.split('/').map(encodeURIComponent).join('/')}`);sha=g.sha;if(g.content)old=b64ToBytes(g.content.replace(/\s/g,''))}catch(e){if(!/Not Found/i.test(e.message))throw e}if(old)$('diff').textContent=simpleDiff(bytesText(bytes),bytesText(old));if(!confirm(`Commit SFTP file to GitHub?\n\n${state.sftpSelected.path}\n→ ${state.ghRepo}:${dest}`))return;await putGh(dest,bytes,$('syncMessage').value,sha);setStatus('syncStatus',`SFTP → GitHub complete: ${dest}`,'good');await loadGh(parent(dest))}catch(e){setStatus('syncStatus',e.message,'bad')}}
function switchTab(name){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('on',x.dataset.tab===name));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('on',x.id===`tab-${name}`))}

document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
$('connect').onclick=connect;$('disconnect').onclick=disconnect;$('refresh').onclick=()=>loadSftp(state.path).catch(showSftpErr);$('go').onclick=()=>loadSftp($('path').value).catch(showSftpErr);$('up').onclick=()=>loadSftp(parent(state.path)).catch(showSftpErr);$('filter').oninput=renderSftp;$('newFile').onclick=()=>createFile().catch(showSftpErr);$('newFolder').onclick=()=>createFolder().catch(showSftpErr);$('upload').onchange=e=>uploadFile(e.target.files?.[0]).catch(showSftpErr);$('saveSftp').onclick=saveEditorSftp;$('copyEditor').onclick=()=>navigator.clipboard.writeText($('editor').value);$('downloadEditor').onclick=()=>{const blob=new Blob([$('editor').value],{type:'text/plain'}),url=URL.createObjectURL(blob);chrome.downloads.download({url,filename:basename(state.editorPath)||'editor.txt',saveAs:true});setTimeout(()=>URL.revokeObjectURL(url),5000)};
$('ghConnect').onclick=()=>loadRepos().catch(showGhErr);$('ghForget').onclick=()=>{state.ghToken='';$('ghToken').value='';chrome.storage.session.remove('ghBuddyToken');$('ghRepo').innerHTML='<option value="">Token forgotten</option>';setStatus('ghStatus','GitHub token removed from session storage.')};$('ghRepo').onchange=e=>{state.ghRepo=e.target.value;state.ghPath='';state.ghSelected=null;if(state.ghRepo)loadGh('').catch(showGhErr)};$('ghGo').onclick=()=>loadGh($('ghPath').value).catch(showGhErr);$('ghUp').onclick=()=>loadGh(parent(state.ghPath)).catch(showGhErr);$('ghSave').onclick=saveEditorGh;$('ghDelete').onclick=()=>deleteGh().catch(showGhErr);
$('compare').onclick=compareSelected;$('ghToSftp').onclick=githubToSftp;$('sftpToGh').onclick=sftpToGithub;
loadPrefs().then(()=>{if($('sftpUser').value&&$('sftpPass').value)connect();if(state.ghToken)loadRepos().catch(()=>{})});
