(()=>{
 if(window.__emojiKeysV2Loaded)return;window.__emojiKeysV2Loaded=true;
 const defaultMap={a:'🍎',b:'🍌',c:'🐱',d:'🐶',e:'🐘',f:'🦊',g:'🍇',h:'🏠',i:'🍦',j:'🧃',k:'🥝',l:'🦁',m:'🌙',n:'🥜',o:'🍊',p:'🐧',q:'👑',r:'🌈',s:'⭐',t:'🐯',u:'☂️',v:'🎻',w:'🐋',x:'❌',y:'🪀',z:'🦓'};
 const defaults={configVersion:2,mode:'animate',effect:'float',size:38,duration:700,intensity:3,sound:'off',heatmap:true,streaks:true,map:defaultMap};
 let settings={...defaults,map:{...defaultMap}},counts={},pendingCountWrites=0,lastKeyAt=0,streak=0,audio=null;
 chrome.storage.local.get({emojiKeys:defaults,emojiKeyCounts:{}}).then(x=>{const stored=x.emojiKeys||{},legacy=!Object.prototype.hasOwnProperty.call(stored,'configVersion');settings={...defaults,...stored,map:{...defaultMap,...stored.map}};if(legacy){if(settings.mode==='insert')settings.mode='replace';else if(settings.mode==='replace')settings.mode='both'}counts=x.emojiKeyCounts||{}});
 chrome.storage.onChanged.addListener(c=>{if(c.emojiKeys?.newValue)settings={...defaults,...c.emojiKeys.newValue,map:{...defaultMap,...c.emojiKeys.newValue.map}}});
 const editable=t=>t instanceof HTMLInputElement||t instanceof HTMLTextAreaElement||t?.isContentEditable;
 function anchor(target){const r=target.getBoundingClientRect();let x=r.left+Math.min(r.width*.5,160),y=r.top+Math.min(r.height*.65,45);if(target instanceof HTMLInputElement||target instanceof HTMLTextAreaElement){x=Math.min(innerWidth-30,r.left+Math.min(r.width-10,Math.max(15,(target.selectionStart||0)*7+12)));y=Math.min(innerHeight-25,r.top+Math.min(r.height-8,28))}return{x:Math.max(10,x),y:Math.max(10,y)}}
 function particle(emoji,x,y,opt={}){const d=document.createElement('span'),dur=opt.duration||settings.duration;d.textContent=opt.char||emoji;Object.assign(d.style,{position:'fixed',left:`${x}px`,top:`${y}px`,fontSize:`${opt.size||settings.size}px`,zIndex:'2147483647',pointerEvents:'none',userSelect:'none',lineHeight:'1',filter:'drop-shadow(0 4px 7px #0008)',transform:'translate(-50%,-50%)',transition:`transform ${dur}ms cubic-bezier(.16,.8,.3,1), opacity ${dur}ms ease`,willChange:'transform,opacity'});document.documentElement.appendChild(d);requestAnimationFrame(()=>{d.style.transform=`translate(calc(-50% + ${opt.dx||0}px),calc(-50% + ${opt.dy??-80}px)) scale(${opt.scale||1.45}) rotate(${opt.rot??((Math.random()-.5)*50)}deg)`;d.style.opacity='0'});setTimeout(()=>d.remove(),dur+80)}
 function effect(emoji,target){const a=anchor(target),n=Math.max(1,Math.min(10,+settings.intensity||3)),boost=settings.streaks?Math.min(4,Math.floor(streak/8)):0,total=Math.min(14,n+boost);switch(settings.effect){case'burst':for(let i=0;i<total;i++){const ang=Math.PI*2*i/total,dist=45+Math.random()*45;particle(emoji,a.x,a.y,{dx:Math.cos(ang)*dist,dy:Math.sin(ang)*dist,scale:.75+Math.random()*.7,rot:(Math.random()-.5)*180})}break;case'confetti':for(let i=0;i<total*2;i++)particle(emoji,a.x+(Math.random()-.5)*25,a.y,{size:Math.max(15,settings.size*(.38+Math.random()*.45)),dx:(Math.random()-.5)*150,dy:-40-Math.random()*130,scale:.5+Math.random()*.8,rot:(Math.random()-.5)*360});break;case'trail':for(let i=0;i<total;i++)setTimeout(()=>particle(emoji,a.x-i*8,a.y+i*2,{size:settings.size*(1-i/(total*2)),dx:35+i*7,dy:-65-i*8,scale:.8}),i*24);break;case'rain':for(let i=0;i<total;i++)particle(emoji,Math.random()*innerWidth,-20,{size:settings.size*(.6+Math.random()*.6),dx:(Math.random()-.5)*40,dy:innerHeight+80,duration:Math.max(900,settings.duration*1.7),scale:1});break;case'sparkle':for(let i=0;i<total;i++)particle(i%2?emoji:'✨',a.x+(Math.random()-.5)*35,a.y+(Math.random()-.5)*25,{size:settings.size*(.45+Math.random()*.7),dx:(Math.random()-.5)*90,dy:-30-Math.random()*80,scale:1.8});break;default:particle(emoji,a.x,a.y,{dy:-85,scale:1.6})}}
 function sound(){if(settings.sound==='off')return;try{audio||=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const t=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();const cfg={pop:[520,900,.07,'sine'],typewriter:[150,90,.035,'square'],bubble:[330,650,.09,'sine'],chime:[660,990,.12,'triangle']}[settings.sound]||[440,660,.06,'sine'];o.type=cfg[3];o.frequency.setValueAtTime(cfg[0],t);o.frequency.exponentialRampToValueAtTime(cfg[1],t+cfg[2]);g.gain.setValueAtTime(.06,t);g.gain.exponentialRampToValueAtTime(.001,t+cfg[2]);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+cfg[2])}catch{}}
 function insert(t,v){if(t instanceof HTMLInputElement||t instanceof HTMLTextAreaElement){const a=t.selectionStart??t.value.length,b=t.selectionEnd??a;t.setRangeText(v,a,b,'end');try{t.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:v}))}catch{t.dispatchEvent(new Event('input',{bubbles:true}))}}else if(t.isContentEditable){document.execCommand('insertText',false,v)}}
 function count(k){if(!settings.heatmap)return;counts[k]=(counts[k]||0)+1;pendingCountWrites++;if(pendingCountWrites>=8){pendingCountWrites=0;chrome.storage.local.set({emojiKeyCounts:counts})}}
 document.addEventListener('keydown',e=>{if(settings.mode==='off'||e.ctrlKey||e.metaKey||e.altKey||e.key.length!==1||!editable(e.target))return;const k=e.key.toLowerCase(),em=settings.map[k];if(!em)return;const now=Date.now();streak=now-lastKeyAt<1800?streak+1:1;lastKeyAt=now;count(k);sound();if(settings.mode==='animate'||settings.mode==='both')effect(em,e.target);if(settings.mode==='replace'||settings.mode==='both'){e.preventDefault();e.stopImmediatePropagation();insert(e.target,em)}},true);
 window.addEventListener('pagehide',()=>{if(settings.heatmap)chrome.storage.local.set({emojiKeyCounts:counts})});
})();
